JobHunt/Areas/Admin/Controllers/AccountManageController.cs
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using JobHunt.Models;
using JobHunt.BU.DTO;
using JobHunt.BU.Manage;
using System.Net;
using Microsoft.Owin.Security;
using JobHunt.Model.EF;
using System.Linq;
using System.Collections.Generic;
using System.IO;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Web.Security;
using ClosedXML.Excel;
using System.Data;

namespace JobHunt.Areas.Admin.Controllers
{
    [Authorize(Roles = "Quản trị, Quản lý người tuyển dụng, Quản lý người tìm việc, Quản lý tài khoản")]
    public class AccountManageController : Controller
    {
        private WebMasterManage _webMasterManage = new WebMasterManage();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public AccountManageController()
        {
        }

        public AccountManageController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Admin/AccountManage
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateAccount()
        {
            return View();
        }

        public ActionResult Decentralization(string keyWord, int page = 1, int pageSize = 10)
        {
            var model = _webMasterManage.GetListWebmasterInfoHaveSearchAndPaging(keyWord, page, pageSize);
            ViewBag.keyWord = keyWord;
            ViewBag.stt = (page - 1) * pageSize;

            var GetListRoles = new JobHuntEntities().AspNetRoles.ToList();
            var listRolesDTO = new List<AspNetRoleDTO>();
            var convertdatarole = new ConvertDataAspNetRole();
            foreach (var role in GetListRoles)
            {
                listRolesDTO.Add(convertdatarole.ConvertToDTO(role));
            }
            ViewBag.roles = listRolesDTO;
            return View(model);
        }

        public JsonResult GetListDecentralization(string idUser)
        {
            var roles = UserManager.FindById(idUser).Roles.ToList();
            List<string> rolesdto = new List<string>();
            foreach (var role in roles)
            {
                rolesdto.Add(role.RoleId);
            }
            
            return base.Json(rolesdto, JsonRequestBehavior.AllowGet);
        }

        public JsonResult UpdateDecentralization(List<string> listroles, string idAspNetUser)
        {
            var resultCode = 0;
            try
            {
                //delete all role by iduser
                var getRoles = UserManager.FindById(idAspNetUser).Roles.ToList();
                foreach (var role in getRoles)
                {
                    UserManager.RemoveFromRole(idAspNetUser, _webMasterManage.GetRoleById(role.RoleId).Name);
                }
                //add new role
                foreach (var role in listroles)
                {
                    UserManager.AddToRole(idAspNetUser, role);
                    resultCode = 1;
                }
            }
            catch (Exception)
            {
                resultCode = 0;
            }
            return base.Json(resultCode, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ListAccount()
        {
            var model = _webMasterManage.GetListWebmasterInfos();
            return View(model);
        }

        public JsonResult DeleteAccount(int? idwebmt)
        {
            var resultCode = 0;
            var resultMessage = "";
            var resultStatus = "error";
            if (idwebmt == null || idwebmt == 0)
            {
                resultMessage = "Mã NTV không được để trống";
            }
            else
            {
                resultCode = _webMasterManage.Delete((int)idwebmt);
                if (resultCode == 1)
                {
                    resultMessage = "Xóa thành công";
                    resultStatus = "success";
                }
                else
                {
                    resultMessage = "Đã xảy ra lỗi khi xóa";
                }
            }
            return Json(new { message = resultMessage, status = resultStatus, code = resultCode }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult DetailAccount(int? id)
        {
            ActionResult result;
            if (id == null)
            {
                result = new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                WebmasterInfoDTO infoWebmasterById = this._webMasterManage.GetInfoWebmasterById(id.Value);
                result = !ReferenceEquals(infoWebmasterById, null) ? ((ActionResult)base.View(infoWebmasterById)) : ((ActionResult)base.HttpNotFound());
            }
            return result;
        }


        //export to excel
        [HttpPost]
        public FileResult ExportToExcel(string keyWord, int? Status)
        {
            //Sheet Tổng Quan
            DataTable dtIndex = new DataTable("DanhSachTK");

            dtIndex.Columns.AddRange(new DataColumn[7] {new DataColumn("STT"),
                                                    new DataColumn("Tên đăng nhập"),
                                                    new DataColumn("Tên đầy đủ"),
                                                    new DataColumn("Ngày vào làm"),
                                                    new DataColumn("Vị trí"),
                                                    new DataColumn("Địa chỉ"),
                                                    new DataColumn("Trạng thái")
                                                   });

            var model = _webMasterManage.GetListWebmasterInfosBySearch(keyWord, Status);

            var stt = 0;
            foreach (var webmt in model)
            {
                stt++;
                dtIndex.Rows.Add(stt, webmt.AspNetUserDTO.UserName, webmt.WIFullName, webmt.WIDateStart.Value.ToString("dd-MM-yyyy"), webmt.nameRole, webmt.WIAddress, webmt.WIStatusString);
            }


            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dtIndex);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "DanhSachTK.xlsx");
                }
            }
        }




        public async Task<ActionResult> UpdateAccount(WebmasterInfoDTO accountdto, int typeFix)
        {
            var resultCode = 0;
            var message = "";
            var status = "error";
            try
            {
                accountdto.WIBirthDay = BU.Common.ConvetDate.ParseRequestDate(accountdto.WIBirthdayString);
                if (typeFix == (int)BU.Common.Enum.TypeFix.Add)
                {
                    //register
                    var user = new ApplicationUser { UserName = accountdto.WIUserName, Email = accountdto.WIEmail, PhoneNumber = accountdto.WIPhoneNumber, EmailConfirmed = true };
                    var result = await UserManager.CreateAsync(user, accountdto.WIPassword);
                    if (result.Succeeded)
                    {
                        //Send mail
                        //string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                        //var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                        //await UserManager.SendEmailAsync(user.Id, "Xác nhận tài khoản của bạn", "Vui lòng xác nhận tài khoản của bạn bằng cách nhấp vào <a href=\"" + callbackUrl + "\">đây</a>");

                        //add role
                        switch (accountdto.WIPosition)
                        {
                            case (int)BU.Common.Enum.WIPosition.Admin:
                                {
                                    UserManager.AddToRole(user.Id, "Quản trị");
                                }
                                break;
                            case (int)BU.Common.Enum.WIPosition.ManageNewAndJob:
                                {
                                    UserManager.AddToRole(user.Id, "Quản lý công việc");
                                    UserManager.AddToRole(user.Id, "Quản lý tin tức");
                                }
                                break;
                            case (int)BU.Common.Enum.WIPosition.ManageUser:
                                {
                                    UserManager.AddToRole(user.Id, "Quản lý người tìm việc");
                                    UserManager.AddToRole(user.Id, "Quản lý người tuyển dụng");
                                }
                                break;
                            case (int)BU.Common.Enum.WIPosition.ManageWebsite:
                                {
                                    UserManager.AddToRole(user.Id, "Quản lý quảng cáo");
                                    UserManager.AddToRole(user.Id, "Quản lý thống kê");

JobHunt/Areas/Admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobHunt.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        // GET: Admin/Login
        public ActionResult Index()
        {
            return View();
        }
    }
}

JobHunt/Areas/Admin/Views/AccountManage/Decentralization.cshtml
@using JobHunt.BU.DTO;
@model PagedList.IPagedList<WebmasterInfoDTO>
@{
    ViewBag.Title = "Phân quyền";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var stt = ViewBag.stt;
    var listRole = ViewBag.roles as List<AspNetRoleDTO>;
}
<section class="wrap__content" id="list-hm">
    <div class="listhm main__content" id="list-mt">
        <div class="listhm__top main__banner">
            <div class="row">
                <div class="col-xl-12">
                    <div class="main__title">
                        <h1 class="main__title--content">Phân quyền</h1>
                    </div>
                </div>
                <div class="clear-fix"></div>
            </div>
        </div>
        <div class="content__inner main-content">
            <div class="listhm__content main__list" style="width:65%;float:left">
                <div class="list__top main__list--top" style="width:155%">
                    <form action="@Url.Action("Decentralization","AccountManage")" method="GET" style="padding-left: 25px;">
                        <div class="row">
                            <div class="col-xl-3 col-12">
                                <div class="list__top--search">
                                    <input type="search" name="keyWord" value="@ViewBag.keyWord" class="search_cm_input input-base" placeholder="Nhập từ khóa tìm kiếm . . ." id="textsearchcm">
                                </div>
                            </div>

                            <div class="col-xl-3 col-sm-6 col-12">
                                <button class="btn btn-primary">Tìm kiếm</button>
                                <div class="date">
                                    @*<span>Từ ngày:</span>
                                        <input type="date" class="dateFrom-cm search-date-cm input-base" date="from">*@
                                </div>
                            </div>
                            <div class="col-xl-3 col-sm-6 col-12">
                                <div class="date">
                                    @*<span>Đến ngày:</span>
                                        <input type="date" class="dateTo-cm search-date-cm input-base" date="to">*@
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="clear-fix"></div>
                </div>

                <div class="list__content main__list--content">
                    <span class="total">
                        Tổng số:
                        <span id="hm_total" class="total-content">@Model.TotalItemCount</span>
                    </span>
                    <div class="table__content">
                        <table class="tablehm table--base" id="tablehm">
                            <thead>
                                <tr>
                                    <th class="first index-th text-center"></th>
                                    <th class="text-left">STT</th>
                                    @*<th class="id">Mã KH</th>*@
                                    <th class="text-left">Họ tên</th>
                                    <th class="text-left">Tên đăng nhập</th>
                                    <th class="text-left">Chức vụ</th>
                                </tr>
                            </thead>
                            <tbody id="hm_table">
                                @foreach (var item in Model)
                                {
                                    stt++;
                                    <tr UserId="@item.WI_AspNetUserId" class="userid">
                                        <td class="first tb-index text-center">
                                            <input class="text-center radiouser" type="radio" name="selectUser" value="@item.WebmasterInfoId" id="user_@item.WebmasterInfoId" userRadio />
                                        </td>
                                        <td class="date-td text-left" style="padding:0; width:50px" title="@stt">
                                            <label for="user_@item.WebmasterInfoId" style="line-height:28px;padding:5px 10px;width:100%;font-weight:400">
                                                @stt
                                            </label>
                                        </td>
                                        <td class="date-td text-left" style="padding:0" title="@item.WIFullName">
                                            <label for="user_@item.WebmasterInfoId" style="line-height:28px;padding:5px 10px;width:100%;font-weight:400">
                                                @item.WIFullName
                                            </label>
                                        </td>
                                        <td class="text-left" style="padding:0" title="@item.WIUserName">
                                            <label for="user_@item.WebmasterInfoId" style="line-height:28px;padding:5px 10px;width:100%;font-weight:400">
                                                @item.WIUserName
                                            </label>
                                        </td>
                                        <td class="text-left" style="padding:0" title="@(item.nameRole)">
                                            <label for="user_@item.WebmasterInfoId" style="line-height:28px;padding:5px 10px;width:100%;font-weight:400">
                                                @(item.nameRole)
                                            </label>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="listcm__bottom main__bottom">
                        <div class="row">
                            <div class="col-xl-6 col-6">
                                <div>
                                    <ul class="interactive__btn group-btn">
                                        <li>
                                            @*<a class="historyconstruction-add" id="popupAdd">
                                                    Thêm
                                                </a>*@
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-xl-6 col-6">
                                <div class="list__pagination group-btn text-right">
                                    <div class="list__pagination group-btn">
                                        <ul class="list__pagination group-btn">
                                            <li>
                                                @if (!Model.IsFirstPage)
                                                {
                                                    <a class="btn-prev" href="@Url.Action("","AccountManage",new {keyWord = ViewBag.keyWord ,page = (Model.PageNumber - 1)})">
                                                        <i class="fas fa-fast-backward"></i>
                                                    </a>
                                                }
                                            </li>
                                            <li>
                                                <a class="index-page">
                                                    @Model.PageNumber
                                                </a>
                                            </li>
                                            <li>
                                                @if (!Model.IsLastPage)
                                                {
                                                    <a class="btn-next" href="@Url.Action("", "AccountManage", new { keyWord = ViewBag.keyWord ,page = (Model.PageNumber + 1) })">
                                                        <i class="fas fa-fast-forward"></i>
                                                    </a>
                                                }
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="clear-fix"></div>
                    </div>
                </div>

            </div>
            <div class="listhm__content main__list" style="width:35%;float:left">
                <div class="list__content main__list--content">
                    <div class="table__content">
                        <table class="tablehm table--base" id="tablehm">
                            <thead>
                                <tr>
                                    <th class="first index-th text-center"></th>
                                    @*<th class="id">Mã KH</th>*@
                                    <th class="text-left">Tên Quyền</th>
                                </tr>
                            </thead>
                            <tbody id="role_table">
                                @foreach (var item in listRole)
                                {
                                    stt++;
                                    <tr UserId="@item.Id">
                                        <td class="first tb-index text-center">
                                            <input class="readonly text-center checkboxpq" type="checkbox" value="@item.Name" id="check_@item.Id" />
                                        </td>
                                        <td class="date-td text-left" title="@(item.Name)" style="padding:0">
                                            <label for="check_@item.Id" style="line-height:28px;padding:5px 10px;width:100%">
                                                @item.Name
                                            </label>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="listcm__bottom main__bottom">
                        <div class="row">
                            <div class="col-xl-12 col-12">
                                <div class="list__pagination group-btn text-right" style="position:relative">
                                    <div class="list__pagination group-btn" style="position:absolute; right:50%; transform:translateX(50%)">
                                        <ul class="interactive__btn group-btn">
                                            <li style="padding-right:5px;">
                                                <a id="submitDecentralization">
                                                    Áp Dụng
                                                </a>
                                            </li>
                                            <li>
                                                <a style="color:black">Hủy</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</section>

JobHunt/Areas/Admin/Views/AccountManage/ListAccount.cshtml
@model List<JobHunt.BU.DTO.WebmasterInfoDTO>
@{
    /**/
    ViewBag.Title = "Danh sách tài khoản";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var stt = 0;
}

<section class="wrap__content" id="list-customer">
    <div class="listcm main__content" id="list-customer">
        <div class="listcm__top main__banner">
            <div class="row">
                <div class="col-xl-6 col-md-6 col-12">
                    <div class="main__title">
                        <h1 class="main__title--content">Danh sách thành viên</h1>
                    </div>
                </div>
                <div class="col-xl-6 col-md-6 col-12">

                    <div class="banner-interactive">
                        <ul class="interactive__btn group-btn">
                            <li>
                                <a class="customer-add customer-btn__add" href="@Url.Action("createaccount","accountmanage")">
                                    Thêm
                                </a>
                            </li>
                            <li>
                                <a class="exportexcel--btn">Xuất</a>
                                @using (Html.BeginForm("ExportToExcel", "Customer", FormMethod.Post, new { @class = "disabled", id = "ExportExcel" }))
                                {
                                    <input type="text" value="" class="valuesearch" name="keyWord" />
                                    <input type="text" value="" class="valuestatus" name="Status" />
                                    <input type="submit" value="Xuất" class="exportexcel" />
                                }
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="clear-fix"></div>
            </div>
        </div>
        <div class="listcm__content main__list">

            <div class="list__content main__list--content gridcm">
                <div class="table__content">
                    <table id="example" class="display textable" style="width:100%">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Tên đăng nhập</th>
                                <th>Tên đầy đủ</th>
                                <th>Ngày vào làm</th>
                                <th>Vị trí</th>
                                <th>Địa chỉ</th>
                                <th>Trạng thái</th>
                                <th>Hành động</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Count > 0)
                            {
                                foreach (var webmt in Model)
                                {
                                    stt++;
                                    <tr role="row" class="odd textable" id="trwebmt@(webmt.WebmasterInfoId)">
                                        <td class="sorting_1">@stt</td>
                                        <td class="username" id="username@(webmt.WebmasterInfoId)">@webmt.WIUserName</td>
                                        <td>@webmt.WIFullName</td>
                                        <td>@webmt.WIDateStart.Value.ToString("dd-MM-yyyy")</td>
                                        <td>@webmt.nameRole</td>
                                        <td>@webmt.WIAddress</td>
                                        <td>@webmt.WIStatusString</td>
                                        <td class="option text-center">
                                            <a title="Xóa" class="btn btn-primary btn-update-webmt btn-del-control" href="@Url.Action("detailaccount","accountmanage", new { id = webmt.WebmasterInfoId })">
                                                <i class="far fa-edit"></i>
                                            </a>
                                            <a title="Xóa" class="btn danger btn-del-webmt btn-del-control" input-id-webmt="@webmt.WebmasterInfoId" page-webmt="list" data-toggle="modal" data-target="#exampleModalCenter">
                                                <i class="far fa-trash-alt"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>

            </div>
        </div>

        @* Popup delete *@
        <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Xóa tài khoản</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Bạn có chắc chắn muốn xóa tài khoản <span id="namedelete"></span> không?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                        <button type="button" class="btn btn-primary" id="btn-yes-delete-webmt">Đồng ý</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

JobHunt/Areas/Admin/Views/AccountManage/Login.cshtml
@{
    ViewBag.Title = "Đăng nhập quản lý || Tech Jobs";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutLogin.cshtml";
}

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="~/Assets/admin/images/img-01.png" alt="IMG">
            </div>

            @*<form class="login100-form validate-form">*@
            @using (Html.BeginForm("Login", "AccountManage", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "login100-form validate-form", role = "form", id = "__AjaxAntiForgeryForm" }))
            {
                @Html.AntiForgeryToken()
                <span class="login100-form-title">
                    Đăng nhập quản lý
                </span>

                <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
                    <input class="input100" type="text" name="EmailLogin" placeholder="Email" id="EmailLogin">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="wrap-input100 validate-input" data-validate="Password is required">
                    <input class="input100" type="password" name="PassLogin" placeholder="Password" id="PassLogin">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="container-login100-form-btn">
                    <button class="login100-form-btn" type="submit">
                        Đăng nhập
                    </button>
                </div>

                @*<div class="text-center p-t-12">
                    <span class="txt1">
                        Forgot
                    </span>
                    <a class="txt2" href="#">
                        Username / Password?
                    </a>
                </div>*@
            }

            @*</form>*@
        </div>
    </div>
</div>