JobHunt/Controllers/RecruitJobController.cs
using JobHunt.BU.DTO;
using JobHunt.BU.Manage;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace JobHunt.Controllers
{
    public class RecruitJobController : Controller
    {

        RecruitJobManage recruitJobManage = new RecruitJobManage();
        ProfessionManage ProfessionManage = new ProfessionManage();
        CityManage cityManage = new CityManage();
        RecruitManage recruitManage = new RecruitManage();
        CandidateManage candidateManage = new CandidateManage();
        // GET: RecruitJob
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult ListJobs(string keyWord, int? idcity, int? idprofession, int page = 1, int pageSize = 10)
        {
            //Lấy ra danh sách tất cả danh mục công việc
            ViewBag.ListProfesstions = new SelectList(ProfessionManage.GetAllProfessions(), "ProfessionId", "PFName");

            //Lấy danh sách tỉnh
            ViewBag.ListCities = new SelectList(cityManage.GetAllCities(), "CityId", "CName");

            //Lấy danh sách thể loại công việc
            ViewBag.ListWorkTypes = new WorkTypeManage().GetAllWorkTypes();

            //Lấy danh sách lương
            ViewBag.ListSalaries = new SalaryMange().GetAllSalaries();

            //Lấy danh sách trình độ
            ViewBag.ListLevels = new LevelManage().GetAllLevels();

            //Lấy danh sách kinh nghiệm
            ViewBag.ListExperiences = new ExperienceManage().GetAllExperiences();

            //Search
            var model = recruitJobManage.GetListRecruitJobHaveSearchAndPaging(keyWord, idcity, idprofession, page, pageSize);

            //var suggest
            //ViewBag.SuggestJobs =
            var ListSuggest = new List<RecruitJobDTO>();
            ListSuggest = recruitJobManage.GetAllListRecruitJobs();
            if (idprofession != null)
            {
                var findProfesstion = new ProfessionManage().GetDetailProfession((int)idprofession);
                ListSuggest = ListSuggest.Where(x => x.ProfessionDTO.CareerDTO.CareerId == findProfesstion.CareerDTO.CareerId).ToList();
            }
            else
            {
                ListSuggest = ListSuggest.OrderByDescending(x=>x.RJCount).ToList();
            }
            //if(model.Count() == 0)
            //{

            //}
            ViewBag.ListSuggest = ListSuggest;
            //get search

            ViewBag.keyWord = keyWord;

            return View(model);
        }

        public ActionResult DetailJob(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = recruitJobManage.GetRecruitJobByID((int)id);
            if (model == null)
            {
                return HttpNotFound();
            }

            recruitJobManage.UpdateCounter(model.RecruitJobId);

            //Lấy danh sách công việc phù hợp
            ViewBag.ListRecentJobs = recruitJobManage.GetListRecentJobs(model.WorkTypeDTO.WorkTypeId, model.SalaryDTO.SalaryId, model.RJDistrictId);


            return View(model);
        }
        [Authorize(Roles = "Người tuyển dụng")]
        [ValidateInput(false)]
        public JsonResult PostANewJob(RecruitJobDTO recruitjobdto, int typeFix)
        {
            var message = "";
            var status = "error";
            if (string.IsNullOrEmpty(recruitjobdto.RJTitle) || string.IsNullOrEmpty(recruitjobdto.RJ_Describe) || string.IsNullOrEmpty(recruitjobdto.RJ_Require) || string.IsNullOrEmpty(recruitjobdto.RJBenefit) ||
                recruitjobdto.RJ_ProfessionId == 0 || recruitjobdto.RJ_SalaryId == 0 || recruitjobdto.RJ_LevelId == 0 || recruitjobdto.RJ_ExperienceId == 0 || recruitjobdto.RJ_WorkTypeId == 0
                || string.IsNullOrEmpty(recruitjobdto.RJPosition) || recruitjobdto.RJAmount == 0 ||
                string.IsNullOrEmpty(recruitjobdto.RJPhoneContact) || string.IsNullOrEmpty(recruitjobdto.RJNameContact) || string.IsNullOrEmpty(recruitjobdto.RJEmailContact) || recruitjobdto.RJCityId == 0 || recruitjobdto.RJDistrictId == 0 || string.IsNullOrEmpty(recruitjobdto.RJ_WorkPlace))
            {
                //Điền đủ thông tin bắt buộc.
                message = "Hãy điền đủ thông tin bắt buộc.";
            }
            else
            {
                if (typeFix == (int)JobHunt.BU.Common.Enum.TypeFix.Add)
                {
                    recruitjobdto.RJCount = 0;
                    recruitjobdto.RJPostDate = DateTime.Now;
                    recruitjobdto.RJStatus = (int?)BU.Common.Enum.EnumStatusJob.Approvaling;
                    recruitjobdto.RJ_RecruitId = recruitManage.GetRecruitInfoByIdAspNetUser(User.Identity.GetUserId()).RecruitId;
                    recruitjobdto.RJType = (int?)BU.Common.Enum.EnumTypeJob.Normal;
                    var insert = recruitJobManage.Insert(recruitjobdto);
                    if (insert != null)
                    {
                        message = "Tin đăng thành công. Tin đang đợi admin phê duyệt. Thời gian phê duyệt trong vòng 24h.";
                        status = "success";
                        string path = Server.MapPath("/Assets/template/SendMailToRegisterTinRao.html");
                        ParameterizedThreadStart job = new ParameterizedThreadStart(SendEmail);
                        Thread thread = new Thread(job);
                        thread.Start(new EmailClient() { TieuDe = insert.RJTitle, Path = path, IdPro = insert.RJ_ProfessionId, job = insert });
                    }
                }
                else
                {
                    var getJob = recruitJobManage.GetRecruitJobByID(recruitjobdto.RecruitJobId);
                    recruitjobdto.RJStatus = getJob.RJStatus;
                    recruitjobdto.RJType = (int?)BU.Common.Enum.EnumTypeJob.Normal;
                    if (recruitJobManage.UpdateJob(recruitjobdto) != 0)
                    {
                        message = "Sửa thông tin thành công.";
                        status = "success";
                    }
                    else
                    {
                        message = "Đã xảy ra lỗi trong quá trình sửa. Hãy thử lại sau.";
                        status = "error";
                    }
                }

            }
            return Json(new { message = message, status = status }, JsonRequestBehavior.AllowGet);
        }

        class EmailClient
        {
            public string TieuDe { get; set; }
            public string Hinhthuc { get; set; }
            public string Path { get; set; }
            public int? IdPro { get; set; }
            public RecruitJobDTO job { get; set; }
        }
        // string tieuDe, int codeInsert, string hinhthuc
        static void SendEmail(object obj)
        {
            var job = obj as EmailClient;
            var getListRegisters = new SignUpNewsletterManage().GetListSignUpByType(1, job.IdPro);
            foreach (var j in getListRegisters)
            {
                SendMailToRegister(job.Path, j.Name, "tin đăng tuyển dụng", "https://localhost:44315/tuyen-dung/chi-tiet-viec-lam/" + BU.Common.GenerateUrl.GenerateSlug(job.job.RJTitle, job.job.RecruitJobId), j.Email);
            }
        }
        public static int SendMailToRegister(string path, string name, string tenht, string link, string mail)
        {
            int resultCode = 0;
            try
            {
                string content = System.IO.File.ReadAllText(path);
                content = content.Replace("{{name}}", name);
                content = content.Replace("{{tenhinhthuc}}", tenht);
                content = content.Replace("{{link}}", link);
                var senderEmail = new MailAddress("websitedoan@gmail.com", "TechJobs");
                var receiverEmail = new MailAddress(mail);
                var password = "nljkgnluuxfegxnu";
                var sub = "Thông báo từ Tech Jobs";
                var body = content;
                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false,
                    Credentials = new NetworkCredential(senderEmail.Address, password)
                };
                using (var mess = new MailMessage(senderEmail, receiverEmail)
                {
                    Subject = sub,
                    Body = body
                })
                {
                    smtp.Send(mess);
                }
                resultCode = 1;
            }
            catch (Exception)
            {
                resultCode = 2;
            }
            return resultCode;
        }


        public ActionResult UpdateJob(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = recruitJobManage.GetRecruitJobByID((int)id);

            if (model == null)
            {
                return HttpNotFound();
            }
            //Lấy ra danh sách tất cả danh mục công việc
            ViewBag.ListProfesstions = new SelectList(ProfessionManage.GetAllProfessions(), "ProfessionId", "PFName");

            //Lấy danh sách tỉnh
            ViewBag.ListCities = new SelectList(cityManage.GetAllCities(), "CityId", "CName");

            //Lấy danh sách trình độ
            ViewBag.ListLevels = new SelectList(new LevelManage().GetAllLevels(), "LevelInfoId", "LIName");

            //Lấy danh sách kinh nghiệm
            ViewBag.ListExperiences = new SelectList(new ExperienceManage().GetAllExperiences(), "ExperienceId", "EShow");

JobHunt/Areas/Admin/Views/RecruitJobManagement/Index.cshtml
@model List<JobHunt.BU.DTO.RecruitJobDTO>
@{
    ViewBag.Title = "Danh sách công việc";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var stt = 0;
}

<section class="wrap__content" id="list-customer">
    <div class="listcm main__content" id="list-customer">
        <div class="listcm__top main__banner">
            <div class="row">
                <div class="col-xl-6 col-md-6 col-12">
                    <div class="main__title">
                        <h1 class="main__title--content">Danh sách bài đăng tuyển dụng</h1>
                    </div>
                </div>
                <div class="col-xl-6 col-md-6 col-12">

                    <div class="banner-interactive">
                        <ul class="interactive__btn group-btn">
                            <li>
                                <a class="customer-add customer-btn__add" href="@Url.Action("CreateCandidate","CandidateManagement")">
                                    Thêm
                                </a>
                            </li>
                            <li>
                                <a class="exportexcel--btn">Xuất</a>
                                @using (Html.BeginForm("ExportToExcel", "recruitjobmanagement", FormMethod.Post, new { @class = "disabled", id = "ExportExcel" }))
                                {
                                    <input type="text" value="" class="valuesearch" name="keyWord" />
                                    <input type="text" value="" class="valuestatus" name="Status" />
                                    <input type="submit" value="Xuất" class="exportexcel" />
                                }
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="clear-fix"></div>
            </div>
        </div>
        <div class="listcm__content main__list">

            <div class="list__content main__list--content gridcm">
                <div class="table__content">
                    <table id="example" class="display textable" style="width:100%">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th class="abovetitlejob">Tiêu đề tin</th>
                                @*<th>Tên đầy đủ</th>*@
                                <th>Ngày đăng tin</th>
                                <th>Ngày hết hạn</th>
                                <th>Tài khoản đăng tin</th>
                                <th>Loại tin</th>
                                <th>Trạng thái</th>
                                <th>Hành động</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Count > 0)
                            {
                                foreach (var job in Model)
                                {
                                    stt++;
                                    <tr role="row" class="odd textable" id="trjob@(job.RecruitJobId)">
                                        <td class="sorting_1">@stt</td>
                                        <td class="subtitlejob titlejob"><a href="@Url.Action("DetailJob", "RecruitJob", new { id = JobHunt.BU.Common.GenerateUrl.GenerateSlug(job.RJTitle, job.RecruitJobId) })" id="titlejob@(job.RecruitJobId)">@job.RJTitle</a></td>
                                        <td>@job.RJPostDate.Value.ToString("dd-MM-yyyy")</td>
                                        @if (job.RJExpirationDate > DateTime.Now)
                                        {
                                            <td>@job.RJExpirationDate.Value.ToString("dd-MM-yyyy")</td>
                                        }
                                        else
                                        {
                                            <td>Đã hết hạn</td>
                                        }
                                        @if (job.RecruitDTO != null)
                                        {
                                            <td>@job.RecruitDTO.RIUserName</td>

                                        }
                                        else
                                        {
                                            <td>Admin</td>
                                        }
                                        <td>@job.NameType</td>
                                        <td>@job.TrangThai</td>
                                        <td class="option text-center">
                                            <a title="Xóa" class="btn btn-primary btn-update-job btn-del-control" href="@Url.Action("updatejob", "recruitjobmanagement", new { id = job.RecruitJobId })">
                                                <i class="far fa-edit"></i>
                                            </a>
                                            <a title="Xóa" class="btn danger btn-del-job btn-del-control" input-id-job="@job.RecruitJobId" page-job="list" data-toggle="modal" data-target="#exampleModalCenter">
                                                <i class="far fa-trash-alt"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>

            </div>
        </div>

        @* Popup delete *@
        <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Xóa bài đăng tin tức</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Bạn có chắc chắn muốn xóa bài đăng <span id="namedelete"></span> không?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                        <button type="button" class="btn btn-primary btndeletejob">Đồng ý</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>